apiVersion: ecr.metalagman.dev/v1alpha1
kind: ECRAuth
metadata:
  labels:
    app.kubernetes.io/name: ecr-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: ecrauth-sample
spec:
  secretName: regcred
  registries:
    - 123456789012.dkr.ecr.us-east-1.amazonaws.com
    - 210987654321.dkr.ecr.eu-west-1.amazonaws.com
  refreshInterval: 11h
